modLoader="boxlin"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/MaienM/AccessibilityMod/issues/"

[[mods]]
modId="accessibilitymod"
version="${file.jarVersion}"
displayName="Accessibility Mod"
authors="MaienM"
description='''
Things to make modded Minecraft a bit more accessible.

Mostly focussed on colorblindness.
'''

[[dependencies.accessibilitymod]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"
[[dependencies.accessibilitymod]]
	modId="forge"
	mandatory=true
	versionRange="[28,)"
	ordering="NONE"
	side="BOTH"
