modLoader="boxlin"
loaderVersion="[3,)"
issueTrackerURL="https://gitlab.com/maienm/mc-colorblind-tools/issues/"

[[mods]]
modId="colorblindtools"
version="${file.jarVersion}"
displayName="Colorblind Tools"
authors="MaienM"
description='''
Things to make the life of a colorblind person easier.

Mostly though text conveying the same information colors are.
'''

[[dependencies.colorblindtools]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"
[[dependencies.colorblindtools]]
	modId="forge"
	mandatory=true
	versionRange="[28,)"
	ordering="NONE"
	side="BOTH"
